---

- name: add next-dev unit file
  copy:
    src: next-dev.service
    dest: /etc/systemd/system/next-dev.service
    mode: 0644

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: enable next-dev
  systemd:
    name: next-dev
    enabled: yes

- name: start next-dev
  systemd:
    name: next-dev
    state: started


...
